"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/theme";
import { Footer, NavBar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <title>Satyam Kumar</title>
            </head>
            <body className={inter.className}>
                <ThemeProvider>
                    <NavBar />
                    {children}
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
